# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/thomas/Documents/diss

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/thomas/Documents/diss

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thomas/Documents/diss/CMakeFiles /home/thomas/Documents/diss//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thomas/Documents/diss/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named diss

# Build rule for target.
diss: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 diss
.PHONY : diss

# fast build rule for target.
diss/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diss.dir/build.make CMakeFiles/diss.dir/build
.PHONY : diss/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diss.dir/build.make CMakeFiles/diss.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diss.dir/build.make CMakeFiles/diss.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diss.dir/build.make CMakeFiles/diss.dir/main.cpp.s
.PHONY : main.cpp.s

src/Camera.o: src/Camera.cpp.o
.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diss.dir/build.make CMakeFiles/diss.dir/src/Camera.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diss.dir/build.make CMakeFiles/diss.dir/src/Camera.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diss.dir/build.make CMakeFiles/diss.dir/src/Camera.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/Splats.o: src/Splats.cpp.o
.PHONY : src/Splats.o

# target to build an object file
src/Splats.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diss.dir/build.make CMakeFiles/diss.dir/src/Splats.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Splats.cpp.o
.PHONY : src/Splats.cpp.o

src/Splats.i: src/Splats.cpp.i
.PHONY : src/Splats.i

# target to preprocess a source file
src/Splats.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diss.dir/build.make CMakeFiles/diss.dir/src/Splats.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Splats.cpp.i
.PHONY : src/Splats.cpp.i

src/Splats.s: src/Splats.cpp.s
.PHONY : src/Splats.s

# target to generate assembly for a file
src/Splats.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diss.dir/build.make CMakeFiles/diss.dir/src/Splats.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Splats.cpp.s
.PHONY : src/Splats.cpp.s

src/sort.o: src/sort.cpp.o
.PHONY : src/sort.o

# target to build an object file
src/sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diss.dir/build.make CMakeFiles/diss.dir/src/sort.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/sort.cpp.o
.PHONY : src/sort.cpp.o

src/sort.i: src/sort.cpp.i
.PHONY : src/sort.i

# target to preprocess a source file
src/sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diss.dir/build.make CMakeFiles/diss.dir/src/sort.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/sort.cpp.i
.PHONY : src/sort.cpp.i

src/sort.s: src/sort.cpp.s
.PHONY : src/sort.s

# target to generate assembly for a file
src/sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diss.dir/build.make CMakeFiles/diss.dir/src/sort.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/sort.cpp.s
.PHONY : src/sort.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diss.dir/build.make CMakeFiles/diss.dir/src/utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diss.dir/build.make CMakeFiles/diss.dir/src/utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/diss.dir/build.make CMakeFiles/diss.dir/src/utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

tests/plyParseTests.o: tests/plyParseTests.cpp.o
.PHONY : tests/plyParseTests.o

# target to build an object file
tests/plyParseTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/plyParseTests.cpp.o
.PHONY : tests/plyParseTests.cpp.o

tests/plyParseTests.i: tests/plyParseTests.cpp.i
.PHONY : tests/plyParseTests.i

# target to preprocess a source file
tests/plyParseTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/plyParseTests.cpp.i
.PHONY : tests/plyParseTests.cpp.i

tests/plyParseTests.s: tests/plyParseTests.cpp.s
.PHONY : tests/plyParseTests.s

# target to generate assembly for a file
tests/plyParseTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/plyParseTests.cpp.s
.PHONY : tests/plyParseTests.cpp.s

tests/sortTests.o: tests/sortTests.cpp.o
.PHONY : tests/sortTests.o

# target to build an object file
tests/sortTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/sortTests.cpp.o
.PHONY : tests/sortTests.cpp.o

tests/sortTests.i: tests/sortTests.cpp.i
.PHONY : tests/sortTests.i

# target to preprocess a source file
tests/sortTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/sortTests.cpp.i
.PHONY : tests/sortTests.cpp.i

tests/sortTests.s: tests/sortTests.cpp.s
.PHONY : tests/sortTests.s

# target to generate assembly for a file
tests/sortTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/sortTests.cpp.s
.PHONY : tests/sortTests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... diss"
	@echo "... tests"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/Splats.o"
	@echo "... src/Splats.i"
	@echo "... src/Splats.s"
	@echo "... src/sort.o"
	@echo "... src/sort.i"
	@echo "... src/sort.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... tests/plyParseTests.o"
	@echo "... tests/plyParseTests.i"
	@echo "... tests/plyParseTests.s"
	@echo "... tests/sortTests.o"
	@echo "... tests/sortTests.i"
	@echo "... tests/sortTests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

